routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index');

Auth::routes();

Route::group(['middleware' => 'auth'], function() {

  Route::get('/home', 'HomeController@index')->name('home');

  Route::resource('/categories', 'CategoriesController');
  Route::resource('/tags', 'TagsController');
  Route::resource('/posts', 'PostsController');
  Route::get('/trashed-posts', 'PostsController@trashed')->name('trashed.index');
  Route::get('/trashed-posts/{id}', 'PostsController@restore')->name('trashed.restore');
});

Route::middleware(['auth', 'admin'])->group(function() {
  Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
  Route::get('/users', 'UsersController@index')->name('users.index');
  Route::post('/users/{user}/make-admin', 'UsersController@makeAdmin')->name('users.make-admin');
});

Route::middleware(['auth'])->group(function() {
  Route::get('/users/{user}/profile', 'UsersController@edit')->name('users.edit');
  Route::post('/users/{user}/profile', 'UsersController@update')->name('users.update');
});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Post;

class Tag extends Model
{
  protected $fillable = ['name'];

  public function posts() {
    return $this->belongsToMany(Post::class);
  }
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\TagRequest;

use App\Tag;

class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      return view('tags.index')->with('tags', Tag::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TagRequest $request)
    {
      Tag::create($request->all());

        session()->flash('success', 'Tag created successfuly');

        return redirect(route('tags.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
      return view('tags.create')->with('tag', $tag);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(TagRequest $request, Tag $tag)
    {
      $tag->update([
            'name' => $request->name
        ]);

        session()->flash('success', 'tag updated successfuly');
        return redirect(route('tags.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
      $tag->delete();
      return redirect(route('tags.index'));
    }
}

resources/views/tags/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="card card-default">
        <div class="card-header">
            {{ isset($tag) ? "Update Tag" : "Add a new Tag" }}
        </div>
        <div class="card-body">
        <form action="{{ isset($tag) ? route('tags.update', $tag->id) : route('tags.store') }}" method="POST">
                @csrf
                @if (isset($tag))
                    @method('PUT')
                @endif
                <div class="form-group">
                    <label for="tag">Tag Name:</label>
                <input type="text" name="name" class="@error('name') is-invalid @enderror form-control" placeholder="Add a new tag" value="{{ isset($tag) ? $tag->name : "" }}">
                    @error('name')
                        <div class="alert alert-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="form-group">
                    <button class="btn btn-success">
                        {{ isset($tag) ? "Update" : "Add" }}
                    </button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/tags/index.blade.php
@extends('layouts.app')

@section('content')
    @if (session()->has('error'))
      <div class="alert alert-danger">
        {{ session()->get('error') }}
      </div>
    @endif
    <div class="clearfix">
    <a href="{{ route('tags.create') }}" class="btn float-right btn-success" style="margin-bottom: 10px">Add Tag</a>
    </div>
    <div class="card card-default">
        <div class="card-header">All Tags</div>
        <table class="card-body">
            <table class="table">
                <tbody>
                    @foreach ($tags as $tag)
                    <tr>
                        <td>
                        {{ $tag->name }} <span class="ml-2 badge badge-primary">{{$tag->posts->count()}}</span>
                        </td>
                        <td>
                            <form class="float-right ml-2" action="{{route('tags.destroy', $tag->id)}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger btn-sm">
                                    Delete
                                </button>
                            </form>
                        <a href="{{route('tags.edit', $tag->id)}}" class="btn btn-primary float-right btn-sm">Edit</a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection