routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index');

Auth::routes();

Route::group(['middleware' => 'auth'], function() {

  Route::get('/home', 'HomeController@index')->name('home');

  Route::resource('/categories', 'CategoriesController');
  Route::resource('/tags', 'TagsController');
  Route::resource('/posts', 'PostsController');
  Route::get('/trashed-posts', 'PostsController@trashed')->name('trashed.index');
  Route::get('/trashed-posts/{id}', 'PostsController@restore')->name('trashed.restore');
});

Route::middleware(['auth', 'admin'])->group(function() {
  Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
  Route::get('/users', 'UsersController@index')->name('users.index');
  Route::post('/users/{user}/make-admin', 'UsersController@makeAdmin')->name('users.make-admin');
});

Route::middleware(['auth'])->group(function() {
  Route::get('/users/{user}/profile', 'UsersController@edit')->name('users.edit');
  Route::post('/users/{user}/profile', 'UsersController@update')->name('users.update');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Category;
use App\Tag;
use App\User;

class Post extends Model
{
  use SoftDeletes;

  protected $fillable = ['title', 'description', 'content', 'image', 'category_id','user_id'];

  public function category() {
    return $this->belongsTo(Category::class);
  }

  public function tags() {
    return $this->belongsToMany(Tag::class);
  }

  public function hasTag($tagId) {
    return in_array($tagId, $this->tags->pluck('id')->toArray());
  }

  public function user() {
    return $this->belongsTo(User::class);
  }


}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use App\Category;
use App\Tag;
use App\Http\Requests\PostRequest;
use App\Http\Requests\UpdatePostRequest;
use Illuminate\Support\Facades\Storage;

class PostsController extends Controller
{

  public function __construct() {
    $this->middleware('checkCategory')->only('create');
  }

  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    return view('posts.index')->with('posts', Post::all());
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    return view('posts.create')->with('categories', Category::all())->with('tags', Tag::all());
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(PostRequest $request)
  {
    $post = Post::create([
      'title' => $request->title,
      'description' => $request->description,
      'content' => $request->content,
      'image' => $request->image->store('images', 'public'),
      'category_id' => $request->categoryID,
      'user_id' => $request->user_id
    ]);

    if ($request->tags) {
      $post->tags()->attach($request->tags);
    }

    session()->flash('success', 'post created successfully');
    return redirect(route('posts.index'));
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show(Post $post)
  {
    $user = $post->user;
    $profile = $user->profile;
    return view("posts.show")->with('post',$post)->with('categories',Category::all())->with('profile',$profile)->with('user',$user);
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit(Post $post)
  {
    return view('posts.create', ['post' => $post, 'categories' => Category::all(), 'tags' => Tag::all()]);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(UpdatePostRequest $request,Post $post)
  {

    $data = $request->only(['title', 'description', 'content']);
    if ($request->hasFile('image')) {
      $image = $request->image->store('images', 'public');
      Storage::disk('public')->delete($post->image);
      $data['image'] = $image;
    }

    if ($request->tags) {
      $post->tags()->sync($request->tags);
    }

    $post->update($data);

    session()->flash('success', 'post updated successfully');
    return redirect(route('posts.index'));
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy($id)
  {
      $post = Post::withTrashed()->where('id', $id)->first();
      if ($post->trashed()) {
          Storage::disk('public')->delete($post->image);
          $post->forceDelete();
      } else {
          $post->delete();
      }
      session()->flash('success', 'post trashed successfully');
      return redirect(route('posts.index'));
  }

  public function trashed() {
      $trashed = Post::onlyTrashed()->get();
      return view('posts.index')->withPosts($trashed);
  }

  public function restore($id) {
    Post::withTrashed()->where('id', $id)->restore();
    session()->flash('success', 'post restored successfully');
    return redirect(route('posts.index'));
  }
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('stylesheets')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.0/trix.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />
@endsection
@section('content')
    <div class="card card-default">
        <div class="card-header">
            {{ isset($post) ? "Update Post" : "Add a new Post" }}
        </div>
        <div class="card-body">
        <form action="{{ isset($post) ? route('posts.update', $post->id) : route('posts.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                @if (isset($post))
                  @method('PUT')
                @endif
                <div class="form-group">
                    <label for="post title">Title:</label>
                <input type="text" class="form-control" name="title" placeholder="Add a new post" value="{{ isset($post) ? $post->title : "" }}">
                </div>
                <div class="form-group">
                    <label for="post description">Description:</label>
                    <textarea class="form-control" rows="2" name="description" placeholder="Add a description">{{ isset($post) ? $post->description : "" }}</textarea>
                </div>
                <div class="form-group">
                    <label for="post content">content:</label>
                    {{-- <textarea class="form-control" rows="3" name="content" placeholder="Add a content"></textarea> --}}
                    <input id="x" type="hidden" name="content" value="{{ isset($post) ? $post->content : "" }}">
                    <trix-editor input="x"></trix-editor>
                </div>
                @if (isset($post))
                  <div class="form-group">
                    <img src="{{asset('storage/' . $post->image)}}" style="width: 100%" />
                  </div>
                @endif
                <div class="form-group">
                    <label for="post image">Image:</label>
                    <input type="file" class="form-control" name="image">
                </div>
                <div class="form-group">
                  <label for="selectCategory">Select a category</label>
                  <select name="categoryID" class="form-control" id="selectCategory">
                    @foreach ($categories as $category)
                      <option value="{{$category->id}}">{{$category->name}}</option>
                    @endforeach
                  </select>
                </div>
                @if (!$tags->count() <= 0 && isset($post))
                  <div class="form-group">
                    <label for="selectTag">Select a tag</label>
                    <select name="tags[]" class="form-control tags" id="selectTag" multiple>
                      @foreach ($tags as $tag)
                        <option value="{{$tag->id}}"
                          @if ($post->hasTag($tag->id))
                            selected
                          @endif
                          >
                          {{$tag->name}}
                        </option>
                      @endforeach
                    </select>
                  </div>
                @endif
                <input type="hidden" name="user_id" value="{{ Auth::user()->id }}">
                <div class="form-group">
                    <button type="submit" class="btn btn-success">
                        {{ isset($post) ? "Update" : "Add" }}
                    </button>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.0/trix.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"></script>

    <script>
      $(document).ready(function() {
        $('.tags').select2();
      });
    </script>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')
  <div class="clearfix">
    <a href="{{ route('posts.create') }}"
    class="btn float-right btn-success"
    style="margin-bottom: 10px">
      Add Post
    </a>
  </div>
  <div class="card card-default">
    <div class="card-header">All Posts</div>
        @if ($posts->count() > 0)
          <table class="card-body">
            <table class="table">
              <thead>
                <tr>
                  <th>Image</th>
                  <th>Title</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                @foreach ($posts as $post)
                  <tr>
                    <td>
                      <img src="{{ asset('storage/'.$post->image) }}" alt="" width="100px" height="50px">
                    </td>
                    <td>
                      {{ $post->title }}
                    </td>
                    <td>
                      <form class="float-right ml-2"
                      action="{{route('posts.destroy', $post->id)}}" method="POST">
                        @csrf
                        @method('DELETE')
                          <button class="btn btn-danger btn-sm">
                            {{ $post->trashed() ? 'Delete' : 'Trash' }}
                        </button>
                      </form>
                      @if (!$post->trashed())
                        <a href="{{route('posts.edit', $post->id)}}" class="btn btn-primary float-right btn-sm">Edit</a>
                      @else
                        <a href="{{route('trashed.restore', $post->id)}}" class="btn btn-primary float-right btn-sm">Restore</a>
                      @endif
                    </td>
                  </tr>
                @endforeach
              </tbody>
          </table>
        @else
          <div class="card-body">
            <h1 class="text-center">
              No Posts Yet.
            </h1>
          </div>
        @endif
    </div>
  </div>
@endsection